// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddAttachmentReducer from "../add_attachment_reducer";
import AddGroupMemberReducer from "../add_group_member_reducer";
import AddReactionReducer from "../add_reaction_reducer";
import ArchiveConversationReducer from "../archive_conversation_reducer";
import CheckEmailExistsReducer from "../check_email_exists_reducer";
import CreateDirectConversationReducer from "../create_direct_conversation_reducer";
import CreateGroupConversationReducer from "../create_group_conversation_reducer";
import CreateNotificationReducer from "../create_notification_reducer";
import DeleteMessageReducer from "../delete_message_reducer";
import DeleteNotificationReducer from "../delete_notification_reducer";
import DemoteFromAdminReducer from "../demote_from_admin_reducer";
import EditMessageReducer from "../edit_message_reducer";
import LeaveConversationReducer from "../leave_conversation_reducer";
import LoginWithEmailReducer from "../login_with_email_reducer";
import MarkAllNotificationsReadReducer from "../mark_all_notifications_read_reducer";
import MarkAsReadReducer from "../mark_as_read_reducer";
import MarkNotificationReadReducer from "../mark_notification_read_reducer";
import MuteConversationReducer from "../mute_conversation_reducer";
import PinMessageReducer from "../pin_message_reducer";
import PromoteToAdminReducer from "../promote_to_admin_reducer";
import RegisterUserReducer from "../register_user_reducer";
import RemoveGroupMemberReducer from "../remove_group_member_reducer";
import RemoveReactionReducer from "../remove_reaction_reducer";
import RequestEmailVerificationReducer from "../request_email_verification_reducer";
import SendMessageReducer from "../send_message_reducer";
import SendMessageWithAttachmentReducer from "../send_message_with_attachment_reducer";
import SetPresenceReducer from "../set_presence_reducer";
import StartTypingReducer from "../start_typing_reducer";
import StopTypingReducer from "../stop_typing_reducer";
import TransferOwnershipReducer from "../transfer_ownership_reducer";
import UnarchiveConversationReducer from "../unarchive_conversation_reducer";
import UnmuteConversationReducer from "../unmute_conversation_reducer";
import UnpinMessageReducer from "../unpin_message_reducer";
import UpdateGroupReducer from "../update_group_reducer";
import UpdateProfileReducer from "../update_profile_reducer";
import UpdateUsernameReducer from "../update_username_reducer";
import VerifyEmailAndRegisterReducer from "../verify_email_and_register_reducer";

export type AddAttachmentParams = __Infer<typeof AddAttachmentReducer>;
export type AddGroupMemberParams = __Infer<typeof AddGroupMemberReducer>;
export type AddReactionParams = __Infer<typeof AddReactionReducer>;
export type ArchiveConversationParams = __Infer<typeof ArchiveConversationReducer>;
export type CheckEmailExistsParams = __Infer<typeof CheckEmailExistsReducer>;
export type CreateDirectConversationParams = __Infer<typeof CreateDirectConversationReducer>;
export type CreateGroupConversationParams = __Infer<typeof CreateGroupConversationReducer>;
export type CreateNotificationParams = __Infer<typeof CreateNotificationReducer>;
export type DeleteMessageParams = __Infer<typeof DeleteMessageReducer>;
export type DeleteNotificationParams = __Infer<typeof DeleteNotificationReducer>;
export type DemoteFromAdminParams = __Infer<typeof DemoteFromAdminReducer>;
export type EditMessageParams = __Infer<typeof EditMessageReducer>;
export type LeaveConversationParams = __Infer<typeof LeaveConversationReducer>;
export type LoginWithEmailParams = __Infer<typeof LoginWithEmailReducer>;
export type MarkAllNotificationsReadParams = __Infer<typeof MarkAllNotificationsReadReducer>;
export type MarkAsReadParams = __Infer<typeof MarkAsReadReducer>;
export type MarkNotificationReadParams = __Infer<typeof MarkNotificationReadReducer>;
export type MuteConversationParams = __Infer<typeof MuteConversationReducer>;
export type PinMessageParams = __Infer<typeof PinMessageReducer>;
export type PromoteToAdminParams = __Infer<typeof PromoteToAdminReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type RemoveGroupMemberParams = __Infer<typeof RemoveGroupMemberReducer>;
export type RemoveReactionParams = __Infer<typeof RemoveReactionReducer>;
export type RequestEmailVerificationParams = __Infer<typeof RequestEmailVerificationReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SendMessageWithAttachmentParams = __Infer<typeof SendMessageWithAttachmentReducer>;
export type SetPresenceParams = __Infer<typeof SetPresenceReducer>;
export type StartTypingParams = __Infer<typeof StartTypingReducer>;
export type StopTypingParams = __Infer<typeof StopTypingReducer>;
export type TransferOwnershipParams = __Infer<typeof TransferOwnershipReducer>;
export type UnarchiveConversationParams = __Infer<typeof UnarchiveConversationReducer>;
export type UnmuteConversationParams = __Infer<typeof UnmuteConversationReducer>;
export type UnpinMessageParams = __Infer<typeof UnpinMessageReducer>;
export type UpdateGroupParams = __Infer<typeof UpdateGroupReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;
export type UpdateUsernameParams = __Infer<typeof UpdateUsernameReducer>;
export type VerifyEmailAndRegisterParams = __Infer<typeof VerifyEmailAndRegisterReducer>;

