// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Conversation = __t.object("Conversation", {
  conversationId: __t.u64(),
  conversationType: __t.string(),
  name: __t.option(__t.string()),
  description: __t.option(__t.string()),
  avatarUrl: __t.option(__t.string()),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  isArchived: __t.bool(),
});
export type Conversation = __Infer<typeof Conversation>;

export const ConversationParticipant = __t.object("ConversationParticipant", {
  participantId: __t.u64(),
  conversationId: __t.u64(),
  userIdentity: __t.identity(),
  role: __t.string(),
  joinedAt: __t.timestamp(),
  isMuted: __t.bool(),
  mutedUntil: __t.option(__t.timestamp()),
  lastReadMessageId: __t.option(__t.u64()),
  isArchived: __t.bool(),
  nickname: __t.option(__t.string()),
});
export type ConversationParticipant = __Infer<typeof ConversationParticipant>;

export const EmailVerification = __t.object("EmailVerification", {
  email: __t.string(),
  verificationCode: __t.string(),
  identity: __t.identity(),
  username: __t.string(),
  displayName: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type EmailVerification = __Infer<typeof EmailVerification>;

export const FileAttachment = __t.object("FileAttachment", {
  attachmentId: __t.u64(),
  messageId: __t.u64(),
  fileName: __t.string(),
  fileType: __t.string(),
  fileSize: __t.u64(),
  fileUrl: __t.string(),
  thumbnailUrl: __t.option(__t.string()),
  uploadedAt: __t.timestamp(),
});
export type FileAttachment = __Infer<typeof FileAttachment>;

export const Message = __t.object("Message", {
  messageId: __t.u64(),
  conversationId: __t.u64(),
  senderIdentity: __t.identity(),
  content: __t.string(),
  messageType: __t.string(),
  replyToMessageId: __t.option(__t.u64()),
  threadRootId: __t.option(__t.u64()),
  sentAt: __t.timestamp(),
  editedAt: __t.option(__t.timestamp()),
  isDeleted: __t.bool(),
  isPinned: __t.bool(),
  metadata: __t.option(__t.string()),
});
export type Message = __Infer<typeof Message>;

export const MessageReaction = __t.object("MessageReaction", {
  reactionId: __t.u64(),
  messageId: __t.u64(),
  userIdentity: __t.identity(),
  emoji: __t.string(),
  createdAt: __t.timestamp(),
});
export type MessageReaction = __Infer<typeof MessageReaction>;

export const Notification = __t.object("Notification", {
  notificationId: __t.u64(),
  userIdentity: __t.identity(),
  notificationType: __t.string(),
  title: __t.string(),
  body: __t.string(),
  data: __t.option(__t.string()),
  isRead: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Notification = __Infer<typeof Notification>;

export const ReadReceipt = __t.object("ReadReceipt", {
  receiptId: __t.u64(),
  messageId: __t.u64(),
  userIdentity: __t.identity(),
  readAt: __t.timestamp(),
});
export type ReadReceipt = __Infer<typeof ReadReceipt>;

export const TypingIndicator = __t.object("TypingIndicator", {
  typingId: __t.u64(),
  conversationId: __t.u64(),
  userIdentity: __t.identity(),
  startedAt: __t.timestamp(),
});
export type TypingIndicator = __Infer<typeof TypingIndicator>;

export const User = __t.object("User", {
  identity: __t.identity(),
  userId: __t.u64(),
  email: __t.string(),
  emailVerified: __t.bool(),
  username: __t.string(),
  displayName: __t.option(__t.string()),
  avatarUrl: __t.option(__t.string()),
  statusMessage: __t.option(__t.string()),
  online: __t.bool(),
  lastSeen: __t.timestamp(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const UserCounter = __t.object("UserCounter", {
  id: __t.u32(),
  nextUserId: __t.u64(),
});
export type UserCounter = __Infer<typeof UserCounter>;

export const UserPresence = __t.object("UserPresence", {
  userIdentity: __t.identity(),
  status: __t.string(),
  customStatus: __t.option(__t.string()),
  lastActivity: __t.timestamp(),
});
export type UserPresence = __Infer<typeof UserPresence>;

export const UserSession = __t.object("UserSession", {
  sessionId: __t.u64(),
  userIdentity: __t.identity(),
  deviceInfo: __t.option(__t.string()),
  ipAddress: __t.option(__t.string()),
  connectedAt: __t.timestamp(),
  lastActive: __t.timestamp(),
});
export type UserSession = __Infer<typeof UserSession>;

